services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: azzazkhan/express
        environment:
            PORT: 3000
        ports:
            - '3000:3000'
